README-zh_cn.md
README.md

[ISSUE #2] explain develop plan

---

README-zh_cn.md
README.md

[ISSUE #27]Correcting typos in the documentation

---

README-zh_cn.md
README.md

close #34 
- Update README.md doc about how to start name server

[ISSUE #34] Update README.md doc about how to start name server

---

rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/runtime/server.rs

close #115 
- Client disconnected and deregistered from Broker

[ISSUE #115]🚀Client disconnected and deregistered from Broker 🚀

---

rocketmq-common/Cargo.toml
rocketmq-common/README.md
rocketmq-macros/Cargo.toml
rocketmq-macros/README.md
rocketmq-remoting/Cargo.toml
rocketmq-remoting/README.md

close #125 
- Add README.md for every crate

[ISSUE #125]📝Add README.md for every crate

---

rocketmq-common/src/common/message.rs
rocketmq-store/Cargo.toml
rocketmq-store/src/base.rs
rocketmq-store/src/base/message_result.rs
rocketmq-store/src/base/message_status_enum.rs
rocketmq-store/src/base/select_result.rs
rocketmq-store/src/consume_queue.rs
rocketmq-store/src/consume_queue/consume_queue_ext.rs
rocketmq-store/src/filter.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/log_file/mapped_file.rs

close #137 
- Define the rust version of Messagestore based on the Java version of MessageStore

[ISSUE #137]🚀Define the rust version of Messagestore based on the Java version of MessageStore

---

rocketmq-broker/README.md

[ISSUE #162]📝Add Broker README.md

---

rocketmq-broker/src/bin/broker_bootstrap_server.rs
rocketmq-broker/src/broker_config.rs
rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/controller.rs
rocketmq-broker/src/controller/replicas_manager.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-remoting/src/runtime.rs
rocketmq-remoting/src/server.rs
rocketmq-remoting/src/server/config.rs
rocketmq-remoting/src/server/rocketmq_server.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/message_store/local_file_store.rs
rocketmq-store/src/timer/timer_message_store.rs
rust-toolchain.toml

[ISSUE #191]🚀Implementing network communication for the Broker-3

---

rocketmq-broker/src/bin/broker_bootstrap_server.rs
rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/admin_broker_processor.rs
rocketmq-common/src/common/config_manager.rs
rocketmq-remoting/src/runtime.rs
rocketmq-remoting/src/server.rs
rocketmq-remoting/src/server/rocketmq_server.rs
rocketmq-store/src/message_store/local_file_store.rs

[ISSUE #199]Broker net model develop

---

rocketmq-macros/src/request_header_custom.rs

[ISSUE #201]🐛Fix Use RequestHeaderCodec macro cannot find type HashMap in this scope

---

rocketmq-broker/src/bin/broker_bootstrap_server.rs
rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/lib.rs
rocketmq-broker/src/mqtrace.rs
rocketmq-broker/src/mqtrace/send_message_context.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-common/src/common/message.rs
rocketmq-common/src/common/message/message_enum.rs
rocketmq-remoting/src/protocol/header.rs
rocketmq-remoting/src/protocol/header/message_operation_header.rs
rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
rocketmq-remoting/src/protocol/static_topic.rs
rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_context.rs
rocketmq-remoting/src/rpc.rs
rocketmq-remoting/src/rpc/rpc_request_header.rs
rocketmq-remoting/src/server/rocketmq_server.rs
rocketmq-store/src/status.rs

[ISSUE #169]🚀Implementing network communication for the Broker

---

rocketmq-store/Cargo.toml
rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/base/compaction_append_msg_callback.rs
rocketmq-store/src/base/put_message_context.rs
rocketmq-store/src/base/transient_store_pool.rs
rocketmq-store/src/config.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file/mapped_file.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs

[ISSUE #218]📌Implement DefaultMappedFile initialization

---

rocketmq-broker/Cargo.toml
rocketmq-broker/src/broker_controller.rs

[ISSUE #224]🎨Using cfg to solve the problem that the MessageStore trait cannot be converted to an object

---

rocketmq-common/src/common/message.rs
rocketmq-common/src/common/message/message_batch.rs
rocketmq-common/src/common/message/message_single.rs
rocketmq-store/src/config/message_store_config.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_encoder/message_ext_encoder.rs
rocketmq-store/src/message_store/local_file_store.rs

[ISSUE #230]🍻Implement MessageExtEncoder

---

rocketmq-common/src/lib.rs
rocketmq-common/src/utils.rs
rocketmq-common/src/utils/util_all.rs
rocketmq-store/src/base.rs
rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs

[ISSUE #234]🚧Implement  AppendMessageCallback-1

---

rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-store/src/base.rs
rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/base/message_result.rs
rocketmq-store/src/base/select_result.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs

[ISSUE #242]🚀Implement DefaultMappedFile related functions-1

---

rocketmq-broker/Cargo.toml
rocketmq-broker/src/broker_config.rs
rocketmq-broker/src/broker_path_config_helper.rs
rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
rocketmq-broker/src/lib.rs
rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-broker/src/schedule/schedule_message_service.rs
rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
rocketmq-common/src/common/config_manager.rs
rocketmq-remoting/src/protocol.rs
rocketmq-remoting/src/protocol/body/topic_info_wrapper.rs

[ISSUE #244]🚧Implement TopicConfigManager load method

---

rocketmq-broker/src/processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/header/message_operation_header/send_message_response_header.rs

[ISSUE #251]🎨Fix code style error in latest rust nightly version

---

rocketmq-broker/src/broker_config.rs
rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-remoting/src/protocol.rs
rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_detail.rs

[ISSUE #263]🚧Support register borker(request code:103)-1

---

rocketmq-common/src/common/future.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/runtime.rs
rocketmq-remoting/src/runtime/config.rs
rocketmq-remoting/src/runtime/config/client_config.rs
rocketmq-remoting/src/server/rocketmq_server.rs

[ISSUE #270]✨Implement remoting client-1

---

rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/runtime.rs

[ISSUE #274]🚀Implement remoting client-3

---

rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs

[ISSUE #290]🎨Optimize RocketmqDefaultClient code

---

rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_lock_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-broker/src/schedule/schedule_message_service.rs
rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
rocketmq-common/src/common/config_manager.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs

[ISSUE #297]🎨Optimize code struct

---

rocketmq-remoting/src/codec/remoting_command_codec.rs

[ISSUE #303]🎨Remove useless import

---

rocketmq-cli/Cargo.toml
rocketmq-cli/README.md
rocketmq-cli/src/bin/rocketmq_cli.rs
rocketmq-cli/src/command_line.rs
rocketmq-cli/src/content_show.rs
rocketmq-common/Cargo.toml
rocketmq-common/src/common/compression/compression_type.rs
rocketmq-common/src/common/message.rs
rocketmq-common/src/common/message/message_decoder.rs
rocketmq-store/src/log_file/mapped_file.rs
rocketmq-store/src/log_file/mapped_file/default_impl_refactor.rs

[ISSUE #313]🚀Read Commit log file from cmd

---

rocketmq-cli/Cargo.toml
rocketmq-cli/src/content_show.rs

[ISSUE #336]🚀Optimize get i32 of content_show#print_content method

---

rocketmq-store/src/queue/local_file_consume_queue_store.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #345]🎨Optimize recover message

---

rocketmq-store/src/consume_queue/mapped_file_queue.rs

[ISSUE #357]⚡️Replace Arc<parking_lot::Mutex<u64>> with AtomicU64 of MappedFileQueue property

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-common/src/common/attribute/cq_type.rs
rocketmq-common/src/common/config_manager.rs
rocketmq-common/src/utils/message_utils.rs
rocketmq-store/src/base/dispatch_request.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs
rocketmq-store/src/message_store/default_message_store.rs
rocketmq-store/src/queue.rs
rocketmq-store/src/queue/batch_consume_queue.rs
rocketmq-store/src/queue/local_file_consume_queue_store.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #360]🎨Optimize MessageStore recover logic

---

rocketmq-store/src/base/select_result.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/log_file/mapped_file.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs
rocketmq-store/src/log_file/mapped_file/default_impl_refactor.rs
rocketmq-store/src/message_store/default_message_store.rs

[ISSUE #366]🚀Implement ReputMessageService

---

Cargo.toml
rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-common/Cargo.toml
rocketmq-common/src/common.rs
rocketmq-common/src/common/hasher.rs
rocketmq-common/src/common/hasher/string_hasher.rs
rocketmq-common/src/common/message/message_single.rs
rocketmq-common/src/common/mix_all.rs
rocketmq-common/src/utils/util_all.rs
rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs
rocketmq-store/src/message_store/default_message_store.rs
rocketmq-store/src/queue/local_file_consume_queue_store.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #368]🚀Optimize send message logic

---

rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs

[ISSUE #381]⚡️Optimize send message logic⚡️

---

rocketmq-common/src/utils/env_utils.rs

[ISSUE #387]✅Add test case for EnvUtils🚀

---

rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-common/src/common/config_manager.rs

[ISSUE #407]🧑‍💻Optimize ConfigManager code

---

rocketmq-remoting/src/codec/remoting_command_codec.rs
rocketmq-remoting/src/protocol/remoting_command.rs

[ISSUE #409]⚡️Optimize RemotingCommand decode and encode

---

rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-remoting/src/protocol.rs

[ISSUE #411]🐛Fix DataVersion deserialize error

---

rocketmq-broker/src/broker_runtime.rs

[ISSUE #413]🚧Optimize Broker shutdown for TopicConfigManager🚀

---

rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs

[ISSUE #415]🎨Optmize code logic

---

rocketmq-filter/src/utils/bloom_filter_data.rs

[ISSUE #443✅]Add test case for BloomFilterData💚

---

rocketmq-common/src/common.rs
rocketmq-common/src/common/stats.rs

[ISSUE #447]✨ Add stats struct

---

rocketmq-broker/src/processor/send_message_processor.rs

[ISSUE #449]🎨Optimize SendMessageProcessor#process_request method

---

rocketmq-common/src/common/stats.rs
rocketmq-common/src/common/stats/stats_snapshot.rs

[ISSUE #453] 🚧Add StatsSnapshot struct

---

rocketmq-common/src/common/stats.rs
rocketmq-common/src/common/stats/call_snapshot.rs

[ISSUE #455] ✨Add CallSnapshot struct

---

rocketmq-common/Cargo.toml
rocketmq-common/src/common/stats.rs
rocketmq-common/src/common/stats/moment_stats_item.rs
rocketmq-common/src/common/stats/moment_stats_item_set.rs
rocketmq-common/src/common/stats/stats_item.rs
rocketmq-store/src/status.rs
rocketmq-store/src/status/manager/broker_stats_manager.rs
rocketmq-store/src/status/state_getter.rs

[ISSUE #457]🚀Enhance the functionality of BrokerStatsManager

---

rocketmq-common/src/common/statistics/statistics_item.rs

[ISSUE #461]🎉Add StatisticsItem struct 🎉

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/ack_message_processor.rs
rocketmq-broker/src/processor/change_invisible_time_processor.rs
rocketmq-broker/src/processor/consumer_manage_processor.rs
rocketmq-broker/src/processor/end_transaction_processor.rs
rocketmq-broker/src/processor/notification_processor.rs
rocketmq-broker/src/processor/polling_info_processor.rs
rocketmq-broker/src/processor/pop_message_processor.rs
rocketmq-broker/src/processor/pull_message_processor.rs
rocketmq-broker/src/processor/query_assignment_processor.rs
rocketmq-broker/src/processor/query_message_processor.rs
rocketmq-broker/src/processor/reply_message_processor.rs
rocketmq-broker/src/topic.rs
rocketmq-broker/src/topic/topic_queue_mapping_clean_service.rs

[ISSUE #467]🔥Optimize broker start and init

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
rocketmq-broker/src/lib.rs
rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
rocketmq-broker/src/util/hook_utils.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-common/src/utils/util_all.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/message_store/default_message_store.rs

[ISSUE #469]🚀Develop BrokerRuntime initializeBrokerScheduledTasks🚀

---

rocketmq-namesrv/src/route_info/broker_addr_info.rs

[ISSUE #477]✅Add test case for BrokerAddrInfo and  BrokerStatusChangeInfo 🚀

---

Cargo.lock
rocketmq-broker/Cargo.toml
rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-remoting/Cargo.toml
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/client.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs

[ISSUE #479]🔥Optimize broker register and client scan_available_name_srv🎨

---

rocketmq-broker/src/broker_runtime.rs

[ISSUE #508] ✨Add fast broker server

---

rocketmq-common/src/utils/message_utils.rs
rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/base/put_message_context.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/log_file/mapped_file.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs
rocketmq-store/src/log_file/mapped_file/default_impl_refactor.rs
rocketmq-store/src/message_encoder/message_ext_encoder.rs

[ISSUE #512]🔥Implementing Functionality  do append batch messages🚀

---

rocketmq-client/src/implementation/mq_client_api_impl.rs
rocketmq-common/src/common/config_manager.rs
rocketmq-store/src/queue/batch_consume_queue.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #1002]🐛Fix clippy check error on ConfigManager

---

rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-client/src/producer/local_transaction_state.rs
rocketmq-client/src/producer/send_status.rs
rocketmq-common/src/common.rs
rocketmq-common/src/common/consumer/consume_from_where.rs
rocketmq-remoting/src/protocol/body/cm_result.rs
rocketmq-remoting/src/protocol/heartbeat/consume_type.rs
rocketmq-remoting/src/protocol/heartbeat/message_model.rs
rocketmq-remoting/src/protocol/subscription/group_retry_policy_type.rs
rocketmq-store/src/base/store_enum.rs
rocketmq-store/src/config/broker_role.rs
rocketmq-store/src/config/flush_disk_type.rs

[ISSUE #1035]🐛Fix clippy check error

---

rocketmq/src/blocking_queue.rs
rocketmq/src/lib.rs

[ISSUE #1125]🔊Implementing functionality similar to Java's LinkedBlockingQueue in Rust using Tokio🚀

---

rocketmq/src/blocking_queue.rs

[ISSUE #1127]🧪Add test case for BlockingQueue

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/end_transaction_processor.rs
rocketmq-broker/src/transaction/operation_result.rs
rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
rocketmq-broker/src/transaction/queue/message_queue_op_context.rs
rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
rocketmq-broker/src/transaction/queue/transactional_op_batch_service.rs
rocketmq-broker/src/transaction/transactional_message_service.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq/src/blocking_queue.rs

[ISSUE #1097]🚧Support broker receive transaction message-2🔥

---

README.md

[ISSUE #1165]📝Update README.md

---

rocketmq-broker/src/processor/pull_message_processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
rocketmq-client/src/implementation/mq_client_api_impl.rs
rocketmq-common/src/utils/string_utils.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-store/src/log_file/commit_log.rs

[ISSUE #1180]Fix cargo clippy -- -D warnings error

---

rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs

[ISSUE #1212]🐛Fix TopicConfigSerializeWrapper unit test error

---

rocketmq-broker/src/processor/send_message_processor.rs

[ISSUE #1214]🔥Optimize Send message put PROPERTY_UNIQ_CLIENT_MESSAGE_ID_KEYIDX Property

---

rocketmq-broker/src/processor/end_transaction_processor.rs
rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
rocketmq-broker/src/transaction/transactional_message_service.rs

[ISSUE #1136]🚀Support broker receive transaction message-3

---

rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
rocketmq-common/src/common/compression/compression_type.rs
rocketmq-common/src/common/compression/compressor.rs
rocketmq-common/src/common/compression/lz4_compressor.rs
rocketmq-common/src/common/compression/zlib_compressor.rs
rocketmq-common/src/common/compression/zstd_compressor.rs
rocketmq-common/src/common/message/message_decoder.rs

[ISSUE #1228]🚀Implement Java MessageDecoder class encodeUniquely and encode method

---

rocketmq-broker/src/failover/escape_bridge.rs

[ISSUE #1721]⚡️Optimize EscapeBridge struct logic

---

rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_service.rs

[ISSUE #1768]📝Add Doc for RebalanceService struct🔥

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs

[ISSUE #2221]💫Optimize BrokerRuntimeInner#register_increment_broker_data🧑‍💻

---

rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/query_assignment_processor.rs

[ISSUE #2291]🙈Change QueryAssignmentProcessor process_request method return paramter⚡️

---

rocketmq-remoting/src/protocol/remoting_command.rs

[ISSUE #2306]⚡️Remove useless set_cmd_version from RemotingCommand

---

rocketmq-broker/src/processor/pop_message_processor.rs

[ISSUE #2626]🐛Fix PopMessageProcessor#process error acording to Java code🔥

---

.github/workflows/codecov.yml

Potential fix for [https://github.com/mxsm/rocketmq-rust/security/code-scanning/6](https://github.com/mxsm/rocketmq-rust/security/code-scanning/6)
To fix the problem, add a `permissions` block to the workflow file `.github/workflows/codecov.yml`. The block should be placed at the top level (before `jobs:`) to apply to all jobs, unless a job requires different permissions. For this workflow, the jobs only check out code, build, test, and upload coverage, none of which require write access to repository contents. Therefore, the minimal required permission is `contents: read`. If in the future a job needs more permissions, you can override the permissions at the job level. The change should be made by inserting the following block after the `name:` and before `env:` or `jobs:`:
```yaml …
```

Potential fix for code scanning alert no. 6: Workflow does not contain permissions

---

rocketmq-store/src/ha/auto_switch/auto_switch_ha_connection.rs
rocketmq-store/src/ha/default_ha_connection.rs
rocketmq-store/src/ha/default_ha_service.rs
rocketmq-store/src/ha/general_ha_connection.rs
rocketmq-store/src/ha/ha_connection.rs

[ISSUE #3985]🍻Make HAConnection::remote_address return owned String and wire remote SocketAddr through HA layer

---

rocketmq-broker/src/out_api/broker_outer_api.rs

Fixes #3917 
Update GetAllSubscriptionGroupConfig to GetAllMessageRequestMode
Ran cargo clippy and cargo test following the Contribute Guide, after that there were some warnings that had nothing to do with this change. I'm not sure if I should fix 'em.

[ISSUE #3917]🐛Update GetAllSubscriptionGroupConfig to GetAllMessageRequestMode

---

Cargo.lock
rocketmq/Cargo.toml

Fixes #3793 
Remove unused trait-variant workspace dependency from Cargo.toml

[ISSUE #3793]⚡️Remove unused trait-variant workspace dependency from Cargo.toml

---

rocketmq-broker/src/client/consumer_group_event.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
rocketmq-common/src/common/attribute/bool_attribute.rs
rocketmq-common/src/common/config.rs
rocketmq-common/src/common/namesrv/namesrv_config.rs
rocketmq-common/src/utils/cleanup_policy_utils.rs
rocketmq-common/src/utils/queue_type_utils.rs
rocketmq-common/src/utils/util_all.rs
rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
rocketmq-remoting/src/protocol/header/create_topic_request_header.rs
rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
rocketmq-remoting/src/protocol/header/reply_message_request_header.rs
rocketmq-remoting/src/protocol/namespace_util.rs
rocketmq-store/src/ha/ha_connection_state_notification_request.rs
rocketmq-store/src/store/running_flags.rs

#4087 Not completed yet.
Fix #4092 
Clean up existing clippy warnings of types:
- bool_assert_comparison
- assertions_on_constant
All these modifications have been made in the tests module and all the tests passed when running `cargo test`

[ISSUE #4092]♻️Clean up existing clippy warnings of bool_assert_comparison and assertions_on_constant

---

rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_config.rs
rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_machine_room.rs
rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_machine_room_nearby.rs
rocketmq-remoting/src/protocol/body/consume_message_directly_result.rs
rocketmq-remoting/src/protocol/body/consume_status.rs
rocketmq-store/src/base/get_message_result.rs
rocketmq-store/src/base/store_enum.rs
rocketmq-store/src/config/flush_disk_type.rs

#4087 Not complete yet
Fix #4096 
Clean up existing clippy warnings of types:
- clone_on_copy
- needless_borrow
All these modifications have been made in the tests module and all the tests passed when running `cargo test`

[ISSUE #4096]♻️Clean up existing clippy warnings of clone_on_copy and needless_borrow

---

rocketmq-broker/src/broker_path_config_helper.rs
rocketmq-client/examples/batch/callback_batch_producer.rs
rocketmq-client/examples/batch/simple_batch_producer.rs
rocketmq-example/examples/consumer/pop_consumer.rs
rocketmq-store/benches/delivery.rs

#4087 Not complete yet
Fix #4099 
Clean up existing clippy warnings of types:
- vec_init_then_push
- redundant_closure
- useless_conversion

[ISSUE #4099]♻️Clean up existing clippy warnings of vec_init_then_push, redundant_closure and useless_conversion

---

rocketmq-store/src/message_store/local_file_message_store.rs

Fixes #4088 
Add inline annotations to delay level table accessors for improved performance in LocalFileMessageStore

[ISSUE #4088]⚡️Add inline annotations to delay level table accessors
