README-zh_cn.md
README.md

[ISSUE #7]Update README.md doc

---

README-zh_cn.md
README.md

close #9 
- Optimize README.md by adding contributor badges and information about related issues

[ISSUE #9]Optimize README.md by adding contributor badges and information about related issues

---

README-zh_cn.md
README.md

[ISSUE #15]Update README.md doc

---

.github/workflows/ci.yaml
rust-toolchain.toml

close #18 
- Update CI to support stable Rust version

[ISSUE #18]Update CI to support stable Rust version

---

namesrv/src/namesrv_bootstrap.rs
namesrv/src/processor/broker_request_processor.rs

close #6 
- Optimize the deserialization of RemotingCommand

[ISSUE #6]Optimize the deserialization of RemotingCommand

---

README-zh_cn.md
README.md

[ISSUE #21]Update README.md doc

---

Cargo.toml
common/Cargo.toml
common/src/common.rs
common/src/common/namesrv.rs
common/src/common/namesrv/namesrv_config.rs
common/src/lib.rs
common/src/thread_pool.rs
namesrv/Cargo.toml
namesrv/resource/namesrv.toml
namesrv/src/namesrv_bootstrap.rs
namesrv/src/processor.rs
namesrv/src/processor/default_request_processor.rs
namesrv/src/route/route_info_manager.rs
remoting/Cargo.toml
remoting/src/code/request_code.rs
remoting/src/lib.rs
remoting/src/runtime.rs
remoting/src/runtime/config.rs
remoting/src/runtime/config/client_config.rs
remoting/src/runtime/config/net_system_config.rs
remoting/src/runtime/config/server_config.rs
remoting/src/runtime/processor.rs
remoting/src/runtime/remoting_service.rs
remoting/src/runtime/server.rs
remoting/src/runtime/server/remoting_server.rs
remoting/src/runtime/server/server_inner.rs
remoting/src/runtime/server/tokio_remoting_server.rs

close #20 
- Abstracting the server and client and implementation

[ISSUE #20]Abstracting the server and client and implementation

---

README-zh_cn.md
README.md

[ISSUE #25]Update README.md doc

---

README.md

[ISSUE #30]Update README.md doc

---

rocketmq-namesrv/src/bin/bootstrap_server.rs

close #36 
- Support current dir as rocketmq home

[ISSUE #36]Support current dir as rocketmq home

---

README.md

[ISSUE #45]Update README.md doc

---

rocketmq-namesrv/README.md

[ISSUE #48]Add README.md doc for rocketmq-namesrv crate

---

Cargo.toml
rocketmq-macros/Cargo.toml
rocketmq-macros/src/lib.rs
rocketmq-namesrv/Cargo.toml
rocketmq-namesrv/README.md
rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-remoting/src/protocol/command_custom_header.rs
rocketmq-remoting/src/protocol/header/namesrv.rs
rocketmq-remoting/src/protocol/header/namesrv/kv_config_request_header.rs

[ISSUE #40]Support put kv config(request code 100)

---

README.md

[ISSUE #51]Update README.md doc

---

rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/async_client.rs
rocketmq-remoting/src/clients/blocking_client.rs
rocketmq-remoting/src/clients/client.rs
rocketmq-remoting/src/codec/remoting_command_codec.rs
rocketmq-remoting/src/connection.rs
rocketmq-remoting/src/lib.rs
rocketmq-remoting/src/protocol/header.rs
rocketmq-remoting/src/protocol/header/namesrv.rs
rocketmq-remoting/src/protocol/header/namesrv/brokerid_change_request_header.rs
rocketmq-remoting/src/protocol/header/namesrv/register_broker_header.rs
rocketmq-remoting/src/protocol/remoting_command.rs

close #53 
- Perfect support broker register(request code 103)

[ISSUE #53]Perfect support broker register(request code 103)

---

Cargo.toml
rocketmq-common/Cargo.toml
rocketmq-common/src/common/namesrv/namesrv_config.rs
rocketmq-common/src/utils/file_utils.rs
rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
rocketmq-remoting/src/protocol/header/client_request_header.rs

fix #58 
- Fix failed to execute the put kv configuration on namesrv

[ISSUE #58]Fix failed to execute the put kv configuration on namesrv

---

rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-remoting/src/protocol/header/namesrv/kv_config_request_header.rs

closes #62 #41 
- Namesrv support delete kv config(request code 102)

[ISSUE #62]Namesrv support delete kv config(request code 102)

---

README.md
rocketmq-namesrv/README.md

close #69 
- Update Namesrv crate README.md doc

[ISSUE #69]Update Namesrv crate README.md doc

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-remoting/src/code/request_code.rs
rocketmq-remoting/src/protocol/header/namesrv.rs
rocketmq-remoting/src/protocol/header/namesrv/broker_request.rs

close #65
- Namesrv support broker heartbeat(request coe 904)

[ISSUE #65]Namesrv support broker heartbeat(request coe 904)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/body/broker_body.rs
rocketmq-remoting/src/protocol/body/broker_body/broker_member_group.rs
rocketmq-remoting/src/protocol/header/namesrv/broker_request.rs
rocketmq-remoting/src/protocol/remoting_command.rs

close #67 
- :rocket:Namesrv support get broker member group(request code 901)

[ISSUE #67]:rocket:Namesrv support get broker member group(request code 901)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs

close #68 
- Namesrv support get broker cluster info(request code 106)

[ISSUE #68] :art: Namesrv support get broker cluster info(request code 106)

---

rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/header/namesrv.rs
rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs
rocketmq-remoting/src/protocol/route/route_data_view.rs

close #74 
- Namesrv support wipe write perm of boker(request code 205)

[ISSUE #74] :triangular_flag_on_post: Namesrv support wipe write perm of boker(request code 205)

---

README.md
rocketmq-namesrv/README.md

[ISSUE #78] :memo: Update README.md doc

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs

close #75 
- :rocket: Namesrv support add write perm of brober (request code 327)

[ISSUE #75] :rocket: Namesrv support add write perm of brober (request code 327)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/body/topic.rs
rocketmq-remoting/src/protocol/body/topic/topic_list.rs

close #76 
- Namesrv supports get all topic list from name server(request code 206)

[ISSUE #76] :sparkles: Namesrv supports get all topic list from name server(request code 206)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/header/namesrv.rs
rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs

close #82
- Namesrv support delete topic in namesrv (request code 216)

[ISSUE #82] :rocket: Namesrv support delete topic in namesrv (request code 216)

---

rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs

close #83 
- Namesrv support register topic in namesrv (request code 217)

[ISSUE #83] :triangular_flag_on_post: Namesrv support register topic in namesrv (request code 217)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/protocol/header/namesrv/kv_config_header.rs
rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs

close #85 
-  :rocket: Namesrv support get topics by cluster (request code 224)

[ISSUE #85] :rocket: Namesrv support get topics by cluster (request code 224)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs

close #86 
- Namesrv support get system topic list (request code 304)

[ISSUE #86]🎉Namesrv support get system topic list (request code 304)

---

rocketmq-common/src/common.rs
rocketmq-common/src/common/sys_flag.rs
rocketmq-common/src/common/sys_flag/topic_sys_flag.rs
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs

close #87 
- Namesrv support get unit topic list (request code 311)

[ISSUE #87]🏷️Namesrv support get unit topic list (request code 311)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs

close #88 
- Namesrv support get has unit sub topic list (request code 312)

[ISSUE #88]📝Namesrv support get has unit sub topic list (request code 312)

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs

close #89 
- Namesrv support get has unit sub ununit topic list (request code 313)

[ISSUE #89]💚Namesrv support get has unit sub ununit topic list (request code 313)

---

rocketmq-common/src/thread_pool.rs

close #101 
- Refactor thread pool

[ISSUE #101]♻️Refactor thread pool

---

rocketmq-common/src/common/namesrv/namesrv_config.rs
rocketmq-common/src/lib.rs
rocketmq-common/src/thread_pool.rs
rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-namesrv/src/processor/client_request_processor.rs
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-namesrv/src/route_info/broker_addr_info.rs
rocketmq-remoting/src/clients/client.rs
rocketmq-remoting/src/connection.rs
rocketmq-remoting/src/protocol/route/route_data_view.rs
rocketmq-remoting/src/runtime/processor.rs
rocketmq-remoting/src/runtime/server.rs

close #100 
- Add Schedule Service to do scan not active broker

[ISSUE #100]⚡️Add Schedule Service to do scan not active broker

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs

Reverts mxsm/rocketmq-rust#104

Revert "[ISSUE #57]🍻Namesrv support broker unregister(request code 104)🚀"

---

README.md
rocketmq-namesrv/README.md
rocketmq-namesrv/src/processor/default_request_processor.rs

link #57 
- Namesrv support broker unregister(request code 104)

[ISSUE #57]🍻Namesrv support broker unregister(request code 104)🚀

---

rocketmq-common/src/common/namesrv/namesrv_config.rs
rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-namesrv/src/lib.rs
rocketmq-namesrv/src/namesrv_config_parse.rs

close #107 
- Add parsing configuration files for Namesrv

[ISSUE #107] 🔧 Add parsing configuration files for Namesrv

---

rocketmq-common/src/thread_pool.rs
rocketmq-namesrv/src/bin/bootstrap_server.rs

close #109 
- Fix shutdown the namesrv throw execption

[ISSUE #109]🐛 Fix shutdown the namesrv throw execption 🚀

---

rocketmq-namesrv/src/processor/default_request_processor.rs

close #111 
- add some print logs

[ISSUE #111]🔊Add some print logs

---

rocketmq-namesrv/src/route/route_info_manager.rs

close #113 
- Fix unregister broker fail(request code 104)

[ISSUE #113]🐛Fix unregister broker fail(request code 104)

---

rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-namesrv/src/processor/client_request_processor.rs
rocketmq-namesrv/src/processor/default_request_processor.rs

close #117 
- Fix can not get Route info by topic(requst code 105)

[ISSUE #117]🐛Fix can not get Route info by topic(requst code 105)

---

rocketmq-common/Cargo.toml
rocketmq-namesrv/Cargo.toml
rocketmq-remoting/Cargo.toml

[ISSUE #119]Update crate Cargo.toml

---

rocketmq-common/src/lib.rs
rocketmq-namesrv/Cargo.toml
rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq/Cargo.toml

[ISSUE #121] Rename crate rocketmq to rocketmq-rust

---

rocketmq-namesrv/Cargo.toml
rocketmq-remoting/Cargo.toml

[ISSUE #123]Update internal dependency versions

---

Cargo.toml
rocketmq-common/Cargo.toml
rocketmq-macros/Cargo.toml
rocketmq-namesrv/Cargo.toml
rocketmq-remoting/Cargo.toml
rocketmq/Cargo.toml

[ISSUE #127]⬆️Upgrade the version to 0.2.0 for the next version's feature development 

---

rocketmq-macros/src/lib.rs
rocketmq-macros/src/remoting_serializable.rs
rocketmq-macros/src/request_header_custom.rs

close #129 
- Define macros to handle common code for RequestHeader

[ISSUE #129]🥚Define macros to handle common code for RequestHeader 

---

Cargo.toml
rocketmq-broker/Cargo.toml
rocketmq-broker/src/lib.rs
rocketmq-store/Cargo.toml
rocketmq-store/src/lib.rs

[ISSUE #131]🤡init broker and store crate

---

rocketmq-broker/Cargo.toml
rocketmq-broker/src/bin/broker_bootstrap_server.rs
rocketmq-broker/src/command.rs

close #141 
- Add Broker command line parse

[ISSUE #141]💥Add Broker command line parse

---

rocketmq-broker/Cargo.toml
rocketmq-broker/src/bin/broker_bootstrap_server.rs
rocketmq-broker/src/broker_controller.rs
rocketmq-common/src/common.rs
rocketmq-common/src/common/broker.rs
rocketmq-common/src/common/broker/broker_config.rs

close #140
- Add Broker bootstrap

[ISSUE #140]🎨Add Broker bootstrap

---

rocketmq-common/src/common.rs
rocketmq-common/src/common/attribute.rs
rocketmq-common/src/common/attribute/attribute_enum.rs
rocketmq-common/src/common/boundary_type.rs
rocketmq-store/Cargo.toml
rocketmq-store/src/base.rs
rocketmq-store/src/base/dispatch_request.rs
rocketmq-store/src/base/swappable.rs
rocketmq-store/src/config.rs
rocketmq-store/src/config/broker_role.rs
rocketmq-store/src/config/flush_disk_type.rs
rocketmq-store/src/consume_queue.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/lib.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/log_file/mapped_file.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs
rocketmq-store/src/message_store.rs
rocketmq-store/src/message_store/local_file_store.rs
rocketmq-store/src/queue.rs
rocketmq-store/src/queue/consume_queue.rs
rocketmq-store/src/queue/file_queue.rs
rocketmq-store/src/queue/queue_offset_operator.rs

close #144 
- Add the basic code for local file in the store module

[ISSUE #144]🎉Add the basic code for local file in the store module

---

rocketmq-broker/src/bin/broker_bootstrap_server.rs
rocketmq-broker/src/command.rs
rocketmq-common/Cargo.toml
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-common/src/lib.rs
rocketmq-common/src/utils.rs
rocketmq-common/src/utils/env_utils.rs
rocketmq-common/src/utils/parse_config_file.rs
rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-store/src/config/broker_role.rs
rocketmq-store/src/config/flush_disk_type.rs
rocketmq-store/src/config/message_store_config.rs
rocketmq-store/src/lib.rs

close #146 
- Add Broker start method and optimize some code

[ISSUE #146]📈Add Broker start method and optimize some code

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

[ISSUE #148]📝Add issue template

---

rocketmq-common/src/common.rs
rocketmq-common/src/common/config_manager.rs

[ISSUE #154]Add ConfigManage code

---

.github/PULL_REQUEST_TEMPLATE.md

[ISSUE #156]📝Add pull resquest template

---

rocketmq-broker/src/filter.rs
rocketmq-broker/src/filter/manager.rs
rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
rocketmq-broker/src/lib.rs
rocketmq-broker/src/offset.rs
rocketmq-broker/src/offset/manager.rs
rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
rocketmq-broker/src/subscription.rs
rocketmq-broker/src/subscription/manager.rs
rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
rocketmq-broker/src/topic.rs
rocketmq-broker/src/topic/manager.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs

Fixes #158 
- Add some Implementations for ConfigManager trait

[ISSUE #158]🚀Add some Implementations for ConfigManager trait

---

rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs

[ISSUE #165]🐛Fix Broker start error

---

rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-common/src/common/config.rs
rocketmq-common/src/common/topic.rs
rocketmq-remoting/src/protocol.rs

[ISSUE #167]👍Add TopicConfigManager#init method

---

rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/schedule/schedule_message_service.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-store/src/base.rs
rocketmq-store/src/base/store_enum.rs
rocketmq-store/src/config/message_store_config.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/message_store.rs
rocketmq-store/src/message_store/local_file_store.rs
rocketmq-store/src/timer.rs
rocketmq-store/src/timer/timer_message_store.rs

[ISSUE #173](🎉Happy Chinese New Year🎉)Implementing network communication for the Broker-2

---

.github/workflows/ci.yaml
rust-toolchain.toml

[ISSUE #175]👷Update GitHub Actions CI

---

rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/remoting.rs
rocketmq-remoting/src/server.rs
rocketmq-remoting/src/server/rocketmq_server.rs
rust-toolchain.toml

[ISSUE #177]♻️Refactor net model

---

.github/workflows/ci.yaml

[ISSUE #181]💚Add codecov ci

---

.github/workflows/codecov.yml

[ISSUE #185]Update codecov

---

README.md

[ISSUE #187]📝Add some icon into README.md

---

README.md

[ISSUE #189]📝Update README.md

---

README.md

[ISSUE #193]📝Update README.md

---

rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-remoting/src/runtime.rs
rocketmq-remoting/src/runtime/server.rs

[ISSUE #197]🐛Fix Name server shutdown throw exception

---

rocketmq-macros/src/request_header_custom.rs

[ISSUE #203]🐛Fix RequestHeaderCodec macro can not work

---

rocketmq-broker/Cargo.toml
rocketmq-broker/src/broker_config.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-common/src/common/message/message_single.rs
rocketmq-remoting/src/protocol/remoting_command.rs
rocketmq-remoting/src/runtime/server.rs
rocketmq-store/Cargo.toml
rocketmq-store/src/base/message_status_enum.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_store/local_file_store.rs

[ISSUE #209]Support send message and send message v2(request code:10,310)-2

---

rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-common/src/common.rs
rocketmq-common/src/common/attribute/topic_message_type.rs
rocketmq-common/src/common/future.rs
rocketmq-store/src/hook.rs
rocketmq-store/src/hook/put_message_hook.rs
rocketmq-store/src/lib.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/message_store/local_file_store.rs

[ISSUE #220]🚀Implement MessageStore put message-1

---

rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-common/src/common.rs
rocketmq-common/src/common/attribute.rs
rocketmq-common/src/common/attribute/attribute_enum.rs
rocketmq-common/src/common/attribute/cq_type.rs
rocketmq-common/src/common/attribute/topic_attributes.rs
rocketmq-common/src/common/compression.rs
rocketmq-common/src/common/compression/compression_type.rs
rocketmq-common/src/common/macros.rs
rocketmq-common/src/common/sys_flag.rs
rocketmq-common/src/common/sys_flag/message_sys_flag.rs
rocketmq-common/src/lib.rs
rocketmq-common/src/utils.rs
rocketmq-common/src/utils/queue_type_utils.rs
rocketmq-store/src/base/message_result.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/message_store/local_file_store.rs
rocketmq-store/src/queue/consume_queue.rs

[ISSUE #223]🚧Implement MessageStore put message(single message)-2

---

rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
rocketmq-namesrv/src/route/route_info_manager.rs

[ISSUE #232]🐛Fix CI fails to pass the check on the latest version of Rustc

---

Cargo.toml
rocketmq-bytebuf/Cargo.toml
rocketmq-bytebuf/src/byte_buf_impl.rs
rocketmq-bytebuf/src/byte_buf_mut_impl.rs
rocketmq-bytebuf/src/lib.rs

[ISSUE #236]✨Create bytebuf crate for bytes operate

---

rocketmq-broker/src/bin/broker_bootstrap_server.rs

[ISSUE #240]🎨Optimize broker main code

---

Cargo.toml
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-filter/Cargo.toml
rocketmq-filter/src/lib.rs

[ISSUE #249]🚀Init rocketmq-filter crate

---

rocketmq-broker/Cargo.toml
rocketmq-broker/src/filter.rs
rocketmq-broker/src/filter/consumer_filter_data.rs
rocketmq-broker/src/filter/manager.rs
rocketmq-broker/src/filter/manager/consumer_filter_wrapper.rs
rocketmq-broker/src/offset/manager.rs
rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_lock_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
rocketmq-broker/src/schedule/delay_offset_serialize_wrapper.rs
rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
rocketmq-filter/Cargo.toml
rocketmq-filter/src/lib.rs
rocketmq-filter/src/utils.rs
rocketmq-filter/src/utils/bloom_filter_data.rs
rocketmq-remoting/src/protocol.rs
rocketmq-remoting/src/protocol/body/topic_info_wrapper.rs
rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_queue_wrapper.rs
rocketmq-remoting/src/subscription.rs
rocketmq-remoting/src/subscription/group_retry_policy.rs
rocketmq-remoting/src/subscription/simple_subscription_data.rs
rocketmq-remoting/src/subscription/subscription_group_config.rs

[ISSUE #248]💥Implement ConfigManager decode method

---

rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
rocketmq-broker/src/schedule/schedule_message_service.rs
rocketmq-common/src/common/config_manager.rs
rocketmq-common/src/utils/file_utils.rs

[ISSUE #258]Fix loading config File error

---

rocketmq-broker/src/broker_controller.rs
rocketmq-remoting/src/server/rocketmq_server.rs

[ISSUE #260]🐛Fix When broker shutdown will throw exeception

---

rocketmq-common/src/common/future.rs

[ISSUE #]🚀Implement CompletableFuture

---

rocketmq-common/src/common/future.rs

[ISSUE #267]✅Add test case for CompletableFuture

---

rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/remoting.rs
rocketmq-remoting/src/runtime.rs

[ISSUE #272]🚀Implement remoting client-2

---

rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs

[ISSUE #276]🐛Fix client send message error

---

rocketmq-remoting/src/clients.rs

[ISSUE #278]🚀Using pub to modify RemotingClient

---

rocketmq-common/src/thread_pool.rs

[ISSUE #280]⚡️Optimize TokioExecutorService

---

rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/lib.rs
rocketmq-broker/src/out_api.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/error.rs
rocketmq-remoting/src/protocol/body/broker_body/register_broker_body.rs
rocketmq-remoting/src/protocol/body/kv_table.rs
rocketmq-remoting/src/protocol/remoting_command.rs

[ISSUE #282]🚀Support register borker(request code:103)-2

---

rocketmq-broker/src/broker_controller.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
rocketmq-common/src/thread_pool.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_detail.rs
rocketmq-remoting/src/runtime.rs

[ISSUE #284]🚧Support register borker(request code:103)-3

---

rocketmq-broker/src/broker_config.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/ack_message_processor.rs
rocketmq-broker/src/processor/admin_broker_processor.rs
rocketmq-broker/src/processor/change_invisible_time_processor.rs
rocketmq-broker/src/processor/notification_processor.rs
rocketmq-broker/src/processor/peek_message_processor.rs
rocketmq-broker/src/processor/polling_info_processor.rs
rocketmq-broker/src/processor/pop_message_processor.rs
rocketmq-broker/src/processor/pull_message_processor.rs
rocketmq-broker/src/processor/reply_message_processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-common/src/utils/message_utils.rs
rocketmq-namesrv/src/bin/bootstrap_server.rs
rocketmq-namesrv/src/processor/client_request_processor.rs
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/runtime.rs
rocketmq-remoting/src/runtime/processor.rs
rocketmq-remoting/src/runtime/server.rs
rocketmq-remoting/src/server/config.rs
rocketmq-remoting/src/server/rocketmq_server.rs

[ISSUE #286]🎨Replace RequestProcessor#process_request &mut self  with &self

---

rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/remoting.rs
rocketmq-remoting/src/server/rocketmq_server.rs

[ISSUE #293]🎨Change RemotingService start method &mut seft to &self

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/blocking_client.rs
rocketmq-remoting/src/clients/client.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/runtime.rs

[ISSUE #262]🚀Support register borker(request code:103)

---

rocketmq-namesrv/README.md

[ISSUE #307]📝Update name server readme.md

---

Cargo.toml
rocketmq-cmd/Cargo.toml
rocketmq-cmd/src/lib.rs

[ISSUE #309]✨Add rocketmq-cmd crate

---

rocketmq-cli/README.md

[ISSUE #317]📝Update rocketmq-cli README.md

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/client.rs
rocketmq-broker/src/client/client_channel_info.rs
rocketmq-broker/src/client/manager/producer_manager.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/client_manage_processor.rs
rocketmq-remoting/src/protocol.rs
rocketmq-remoting/src/protocol/header.rs
rocketmq-remoting/src/protocol/header/unregister_client_request_header.rs
rocketmq-remoting/src/protocol/remoting_command.rs
rocketmq-remoting/src/rpc/rpc_request_header.rs

[ISSUE #320]✨Support unregister client(requst code 35)

---

rocketmq-broker/README.md

[ISSUE #325]📝Update rocketmq-broker crate README.md

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-store/src/base.rs
rocketmq-store/src/base/allocate_mapped_file_service.rs
rocketmq-store/src/base/store_checkpoint.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/index.rs
rocketmq-store/src/index/index_service.rs
rocketmq-store/src/kv.rs
rocketmq-store/src/kv/compaction_service.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_store/local_file_store.rs

[ISSUE #222]🚀Implement MessageStore put message(single message)

---

rocketmq-store/src/base/commit_log_dispatcher.rs
rocketmq-store/src/base/store_checkpoint.rs
rocketmq-store/src/index.rs
rocketmq-store/src/index/index_dispatch.rs
rocketmq-store/src/index/index_service.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_store/local_file_store.rs
rocketmq-store/src/queue.rs
rocketmq-store/src/queue/build_consume_queue.rs
rocketmq-store/src/queue/local_file_consume_queue_store.rs

[ISSUE #330]🎨Optimize commitlog recover

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/admin_broker_processor.rs
rocketmq-broker/src/processor/client_manage_processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-namesrv/src/bootstrap.rs
rocketmq-namesrv/src/processor.rs
rocketmq-remoting/src/runtime/processor.rs
rocketmq-remoting/src/runtime/server.rs
rocketmq-store/src/base/commit_log_dispatcher.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/index/index_dispatch.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_store/local_file_store.rs
rocketmq-store/src/queue/build_consume_queue.rs
rocketmq-store/src/services/allocate_mapped_file_service.rs

[ISSUE #332]🎨Optmize code struct

---

rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/admin_broker_processor.rs
rocketmq-broker/src/processor/client_manage_processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-namesrv/src/processor.rs
rocketmq-namesrv/src/processor/client_request_processor.rs
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-remoting/src/runtime/processor.rs
rocketmq-remoting/src/runtime/server.rs

[ISSUE #341]🎨Optimize RequestProcessor return

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-broker/src/schedule/schedule_message_service.rs
rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
rocketmq-common/Cargo.toml
rocketmq-common/src/common.rs
rocketmq-common/src/common/attribute.rs
rocketmq-common/src/common/attribute/attribute_enum.rs
rocketmq-common/src/common/attribute/attribute_util.rs
rocketmq-common/src/common/attribute/topic_attributes.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-common/src/common/config.rs
rocketmq-common/src/common/config_manager.rs
rocketmq-common/src/utils/util_all.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/error.rs
rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/message_store/default_message_store.rs

[ISSUE #343]🚀Optimize send message

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-store/src/message_store/default_message_store.rs

[ISSUE #347]🎨Create abort file

---

rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/log_file/mapped_file/default_impl_refactor.rs
rocketmq-store/src/message_store/default_message_store.rs

[ISSUE #350]📌Optimize AppendMessageCallback trait and implemention

---

rocketmq-broker/src/broker.rs
rocketmq-broker/src/broker/broker_hook.rs
rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/lib.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_store/default_message_store.rs
rocketmq-store/src/store.rs
rocketmq-store/src/store/running_flags.rs
rocketmq-store/src/store_path_config_helper.rs

[ISSUE #353]🚩Add Broker shutdown logic

---

rocketmq-remoting/src/lib.rs
rocketmq-store/src/base/store_checkpoint.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_store/default_message_store.rs
rocketmq-store/src/queue.rs
rocketmq-store/src/queue/batch_consume_queue.rs
rocketmq-store/src/queue/consume_queue_ext.rs
rocketmq-store/src/queue/local_file_consume_queue_store.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #362]✨Implment Commit log abort recover

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-broker/src/topic/manager/topic_config_manager.rs
rocketmq-common/src/common.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-common/src/common/config.rs
rocketmq-common/src/common/constant.rs
rocketmq-common/src/utils/queue_type_utils.rs
rocketmq-namesrv/src/processor/default_request_processor.rs
rocketmq-namesrv/src/route/route_info_manager.rs
rocketmq-remoting/src/codec/remoting_command_codec.rs
rocketmq-remoting/src/protocol.rs
rocketmq-remoting/src/protocol/remoting_command.rs
rocketmq-store/src/base/commit_log_dispatcher.rs
rocketmq-store/src/base/store_checkpoint.rs
rocketmq-store/src/consume_queue/mapped_file_queue.rs
rocketmq-store/src/index/index_dispatch.rs
rocketmq-store/src/index/index_service.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/message_store/default_message_store.rs
rocketmq-store/src/queue/build_consume_queue.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #373]✨Optimize broker receive message logic and fix some bugs✨

---

.github/workflows/codecov.yml

Reverts mxsm/rocketmq-rust#372

Revert "Bump codecov/codecov-action from 4.4.0 to 4.4.1"

---

.github/workflows/codecov.yml

[ISSUE #377]⚡️Bump codecov/codecov-action from 4.4.0 to 4.4.1⚡️

---

rocketmq-store/src/config/flush_disk_type.rs
rocketmq-store/src/config/message_store_config.rs
rocketmq-store/src/message_encoder/message_ext_encoder.rs

[ISSUE #385] ✅Add test case for MessageExtEncoder

---

rocketmq-common/Cargo.toml
rocketmq-common/src/utils/file_utils.rs

[ISSUE #389]✅Add test case for file_utils🚀

---

rocketmq-store/src/log_file/mapped_file.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs
rocketmq-store/src/log_file/mapped_file/default_impl_refactor.rs
rocketmq-store/src/message_store/default_message_store.rs
rocketmq-store/src/queue/consume_queue_ext.rs
rocketmq-store/src/queue/local_file_consume_queue_store.rs
rocketmq-store/src/queue/queue_offset_operator.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #395]🔥Implement consume store recoverOffsetTable🚀

---

rocketmq-common/src/common/sys_flag/message_sys_flag.rs

[ISSUE #397]✅Add test case for MessageSysFlag💡

---

rocketmq-common/src/common/sys_flag/topic_sys_flag.rs

[ISSUE #399]✅Add test case for topic_sys_flag🚀

---

rocketmq-common/src/utils/crc32_utils.rs
rocketmq-common/src/utils/util_all.rs

[ISSUE #401]🎨Implement UtilAll method

---

rocketmq-common/src/common/attribute/cleanup_policy.rs
rocketmq-common/src/utils/cleanup_policy_utils.rs

[ISSUE #403]🎨Optimize CleanupPolicyUtils

---

rocketmq-broker/src/topic/manager/topic_config_manager.rs

[ISSUE #405]🍻Optimize TopicConfigManager register_broker_data method

---

rocketmq-store/src/base/message_result.rs
rocketmq-store/src/log_file/commit_log.rs

[ISSUE #421]🚀Optimize and refine the dishwashing process

---

rocketmq-store/src/queue/local_file_consume_queue_store.rs
rocketmq-store/src/queue/queue_offset_operator.rs
rocketmq-store/src/queue/single_consume_queue.rs

[ISSUE #423]🐛Fix after sending the message, the queueOffset did not increase

---

Cargo.toml
rocketmq-broker/Cargo.toml
rocketmq-cli/Cargo.toml
rocketmq-namesrv/Cargo.toml
rocketmq-remoting/Cargo.toml
rocketmq-store/Cargo.toml

[ISSUE #427]⬆️Upgrade the version to 0.3.0 for the next version's feature development📌

---

Cargo.toml
rocketmq-broker/Cargo.toml
rocketmq-cli/Cargo.toml
rocketmq-namesrv/Cargo.toml
rocketmq-remoting/Cargo.toml
rocketmq-store/Cargo.toml

[ISSUE #429]⬆️Upgrade the version to 0.3.0 for the next version's feature development📌

---

distribution/package_publish_workspace.bat
distribution/package_publish_workspace.sh

[ISSUE #431]🔨Add rocketmq rust crate package and publish scripts🔨

---

rocketmq-broker/src/mqtrace/send_message_context.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_queue_wrapper.rs
rocketmq-remoting/src/protocol/header/message_operation_header.rs
rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
rocketmq-remoting/src/protocol/remoting_command.rs
rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_context.rs
rocketmq-remoting/src/rpc.rs
rocketmq-remoting/src/rpc/topic_request_header.rs

[ISSUE #433]👷Improving Methods of TopicQueueMappingManager Struct

---

rocketmq-broker/src/mqtrace.rs
rocketmq-broker/src/mqtrace/send_message_hook.rs
rocketmq-broker/src/processor.rs
rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-common/src/common/broker/broker_config.rs
rocketmq-common/src/common/message/message_single.rs
rocketmq-remoting/src/protocol/remoting_command.rs
rocketmq-store/src/log_file.rs

[ISSUE #435]⚡️Improving broker receive a single message🎨

---

rocketmq-broker/src/processor/send_message_processor.rs

[ISSUE #437]🔥Remove useless code

---

rocketmq-common/src/common/consumer/consume_from_where.rs

[ISSUE #445]✅Add test case for ConsumeFromWhere

---

rocketmq-common/Cargo.toml
rocketmq-common/src/common/stats.rs
rocketmq-common/src/common/stats/moment_stats_item.rs
rocketmq-common/src/utils/util_all.rs

[ISSUE #451] ✨Add MomentStatsItem struct 🚀

---

rocketmq-common/src/common/statistics.rs
rocketmq-common/src/common/statistics/statistics_item.rs
rocketmq-common/src/common/statistics/statistics_item_formatter.rs

[ISSUE #463] ✨Add StatisticsItemFormatter struct

---

rocketmq-common/src/common/statistics.rs
rocketmq-common/src/common/statistics/statistics_item.rs
rocketmq-common/src/common/statistics/statistics_item_scheduled_printer.rs
rocketmq-common/src/common/statistics/statistics_item_state_getter.rs
rocketmq-common/src/common/statistics/statistics_kind_meta.rs
rocketmq-common/src/common/statistics/statistics_manager.rs
rocketmq-store/src/stats/broker_stats_manager.rs

[ISSUE #465]🔖Enhance the functionality of BrokerStatsManager -3

---

rocketmq-remoting/src/clients/blocking_client.rs
rocketmq-remoting/src/clients/client.rs
rocketmq-remoting/src/codec/remoting_command_codec.rs
rocketmq-remoting/src/error.rs

[ISSUE #481] 🍻Optimize error handle

---

rocketmq-broker/src/out_api/broker_outer_api.rs
rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs

[ISSUE #493] 🍻Optimize broker out api registers broker

---

rocketmq-remoting/src/clients.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs

[ISSUE #495]🚀Optimize RemotingClient trait

---

rocketmq-remoting/src/protocol/heartbeat/heartbeat_data.rs

[ISSUE #497]🐛Ensure compatibility with the deserialization of lower versions of HeartbeatData

---

rocketmq-common/src/common/consumer/consume_from_where.rs
rocketmq-remoting/src/protocol/heartbeat/consume_type.rs
rocketmq-remoting/src/protocol/heartbeat/consumer_data.rs
rocketmq-remoting/src/protocol/heartbeat/heartbeat_data.rs
rocketmq-remoting/src/protocol/heartbeat/message_model.rs

[ISSUE #499]🎨Add default value for struct

---

rocketmq-remoting/src/protocol/heartbeat/heartbeat_data.rs

[ISSUE #501] ✅Add test case for HeartbeatData

---

rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-broker/src/util/hook_utils.rs
rocketmq-common/src/common/message/message_batch.rs
rocketmq-common/src/common/message/message_client_id_setter.rs
rocketmq-common/src/common/message/message_decoder.rs
rocketmq-common/src/common/message/message_single.rs
rocketmq-store/src/base/append_message_callback.rs
rocketmq-store/src/base/put_message_context.rs
rocketmq-store/src/config/message_store_config.rs
rocketmq-store/src/log_file.rs
rocketmq-store/src/log_file/commit_log.rs
rocketmq-store/src/log_file/mapped_file.rs
rocketmq-store/src/log_file/mapped_file/default_impl.rs
rocketmq-store/src/log_file/mapped_file/default_impl_refactor.rs
rocketmq-store/src/message_encoder/message_ext_encoder.rs
rocketmq-store/src/message_store/default_message_store.rs

[ISSUE #510]✨Broker supports batch message storage🚀

---

.github/workflows/auto-comment-pr.yml

[ISSUE #529]🔨Optimize Auto Comment on PR

---

rocketmq-common/src/common/attribute/cleanup_policy.rs

[ISSUE #535]✅Add test case for CleanupPolicy

---

.github/workflows/label-on-approval.yml

Update config file

---

.github/workflows/label-on-approval.yml
.github/workflows/work_flow_watch.yml

Mxsm patch 1

---

rocketmq-common/src/common/config.rs
rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
rocketmq-remoting/src/protocol/static_topic/logic_queue_mapping_item.rs
rocketmq-remoting/src/protocol/static_topic/topic_queue_info.rs
rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_detail.rs

[ISSUE #630]✅Add test case for TopicConfigAndMappingSerializeWrapper

---

.github/workflows/auto-comment-pr.yml
.github/workflows/auto_request_review.yml
.github/workflows/automerge.yml

[ISSUE #635]🔧Update actions auto config

---

rocketmq-remoting/src/protocol/body/topic/topic_list.rs

[ISSUE #637]✅ Add test case for TopicList

---

rocketmq-broker/src/long_polling.rs
rocketmq-broker/src/long_polling/long_polling_service/pull_request_hold_service.rs
rocketmq-broker/src/long_polling/message_arriving_listener.rs

[ISSUE ##724]🚀Add MessageArrivingListener

---

Cargo.lock
rocketmq-client/Cargo.toml
rocketmq-client/src/base.rs
rocketmq-client/src/base/mq_admin.rs
rocketmq-client/src/base/query_result.rs
rocketmq-client/src/error.rs

[ISSUE #842]✨Add MQAdmin trait for sdk client🚀

---

rocketmq-client/src/base/client_config.rs
rocketmq-client/src/factory/mq_client_instance.rs
rocketmq-client/src/implementation/mq_admin_impl.rs
rocketmq-client/src/producer/default_mq_producer.rs
rocketmq-client/src/producer/message_queue_selector.rs
rocketmq-client/src/producer/mq_producer.rs
rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
rocketmq-common/src/common/message/message_queue.rs
rocketmq-remoting/src/rpc/client_metadata.rs

[ISSUE #908]Implement mq producer other methods-1

---

rocketmq-client/src/factory/mq_client_instance.rs
rocketmq-client/src/implementation/mq_admin_impl.rs
rocketmq-client/src/producer/default_mq_producer.rs
rocketmq-client/src/producer/mq_producer.rs
rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs

[ISSUE #910]🚀Implement mq producer other methods-2🚀

---

README.md

[ISSUE #918]📝Update README.md

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor/admin_broker_processor.rs
rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
rocketmq-broker/src/processor/consumer_manage_processor.rs
rocketmq-broker/src/processor/pull_message_processor.rs
rocketmq-broker/src/processor/reply_message_processor.rs
rocketmq-remoting/src/clients/client.rs
rocketmq-remoting/src/net/channel.rs
rocketmq-remoting/src/protocol/header.rs
rocketmq-remoting/src/protocol/header/get_max_offset_request_header.rs
rocketmq-remoting/src/protocol/header/get_min_offset_request_header.rs
rocketmq-remoting/src/protocol/header/message_operation_header.rs
rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
rocketmq-remoting/src/protocol/header/query_consumer_offset_request_header.rs
rocketmq-remoting/src/protocol/header/update_consumer_offset_header.rs
rocketmq-remoting/src/remoting_server/server.rs
rocketmq-remoting/src/rpc/rpc_client.rs
rocketmq-remoting/src/rpc/rpc_client_hook.rs
rocketmq-remoting/src/rpc/rpc_client_impl.rs
rocketmq-remoting/src/rpc/rpc_client_utils.rs
rocketmq-remoting/src/rpc/rpc_request.rs

[ISSUE #950]✨Support RequestCode GET_MAX_OFFSET/GET_MIN_OFFSET(30/31) in AdminBrokerProcessor🔥

---

rocketmq-client/examples/quickstart/consumer.rs
rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
rocketmq-client/src/consumer/consumer_impl/message_request.rs
rocketmq-client/src/consumer/consumer_impl/process_queue.rs
rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
rocketmq-client/src/consumer/consumer_impl/pull_message_service.rs
rocketmq-client/src/consumer/consumer_impl/re_balance.rs
rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_service.rs
rocketmq-client/src/consumer/mq_consumer_inner.rs
rocketmq-client/src/consumer/store.rs
rocketmq-client/src/consumer/store/controllable_offset.rs
rocketmq-client/src/consumer/store/local_file_offset_store.rs
rocketmq-client/src/consumer/store/offset_store.rs
rocketmq-client/src/consumer/store/remote_broker_offset_store.rs
rocketmq-client/src/factory/mq_client_instance.rs
rocketmq-client/src/implementation.rs
rocketmq-client/src/implementation/find_broker_result.rs
rocketmq-client/src/implementation/mq_admin_impl.rs
rocketmq-client/src/implementation/mq_client_api_impl.rs
rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
rocketmq-common/src/common/constant.rs
rocketmq-common/src/common/constant/consume_init_mode.rs
rocketmq-common/src/utils/util_all.rs
rocketmq-remoting/src/protocol/body/check_client_request_body.rs
rocketmq-remoting/src/protocol/body/process_queue_info.rs

[ISSUE #967]🚀 Support client consumer message-4 🚀

---

rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
rocketmq-client/src/consumer/consumer_impl/pull_message_service.rs
rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_service.rs
rocketmq-client/src/consumer/mq_consumer_inner.rs
rocketmq-client/src/consumer/pull_callback.rs
rocketmq-client/src/consumer/store/remote_broker_offset_store.rs
rocketmq-client/src/factory/mq_client_instance.rs
rocketmq-client/src/implementation/client_remoting_processor.rs
rocketmq-client/src/implementation/mq_client_manager.rs
rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
rocketmq-remoting/src/clients/rocketmq_default_impl.rs
rocketmq-remoting/src/protocol/header.rs
rocketmq-remoting/src/protocol/header/notify_consumer_ids_changed_request_header.rs

[ISSUE #990]🚀Support NOTIFY_CONSUMER_IDS_CHANGED(request code 40) for client

---

rocketmq-client/src/base/validators.rs

[ISSUE #1123]🧪Add test case for Validators

---

rocketmq/src/blocking_queue.rs

[ISSUE #1129]📝Add doc for BlockingQueue

---

rocketmq-macros/src/request_header_custom.rs

[ISSUE #1140]⚡️Enhanced the RequestHeaderCodec macro

---

.github/workflows/ci.yaml

[ISSUE #1146]Update Github Actions CI

---

Cargo.lock
rocketmq-broker/src/processor/admin_broker_processor/consumer_request_handler.rs
rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
rocketmq-broker/src/processor/default_pull_message_result_handler.rs
rocketmq-client/src/base/client_config.rs
rocketmq-common/src/common/message/message_queue.rs

[ISSUE #1150]Use CheetahString to replace std String in MessageQueue

---

rocketmq-broker/src/processor/send_message_processor.rs
rocketmq-remoting/src/protocol/remoting_command.rs

[ISSUE #1167]🎨Optimize RemotingCommand#with_remark method🎨

---

rocketmq-common/src/log.rs

[ISSUE #1194]🔥Add doc for log.rs🚀

---

.github/workflows/auto-comment-pr.yml

[ISSUE #1202]🔨Upate Github actions CI🔧

---

Cargo.lock
Cargo.toml
rocketmq-broker/Cargo.toml
rocketmq-broker/src/transaction/queue/get_result.rs
rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
rocketmq-client/Cargo.toml
rocketmq-client/README.md
rocketmq-client/examples/batch/callback_batch_producer.rs
rocketmq-client/examples/batch/simple_batch_producer.rs
rocketmq-client/examples/broadcast/push_consumer.rs
rocketmq-client/examples/ordermessage/ordermessage_consumer.rs
rocketmq-client/examples/ordermessage/ordermessage_producer.rs
rocketmq-client/examples/producer/simple_producer.rs
rocketmq-client/examples/quickstart/consumer.rs
rocketmq-client/examples/quickstart/producer.rs
rocketmq-client/examples/rpc/request_callback_producer.rs
rocketmq-client/examples/rpc/request_producer.rs
rocketmq-client/examples/transaction/transaction_producer.rs

[ISSUE #1207]🔥Rename rocketmq-client crate name to rocketmq-client-rust🐛

---

Cargo.lock
Cargo.toml

[ISSUE #1210]✨Update the version to 0.4.0 for development

---

.github/workflows/associate_milestone_issue.yml
.github/workflows/associate_milestone_pr.yml
.github/workflows/auto-comment-pr.yml
.github/workflows/remove-label-on-approve.yml
.github/workflows/sync-issue-labels.yml

Reverts mxsm/rocketmq-rust#1320

Revert "[ISSUE #1319]🔨Update Github Actions CI"

---

.github/workflows/associate_milestone_issue.yml
.github/workflows/associate_milestone_pr.yml
.github/workflows/sync-issue-labels.yml

Reverts mxsm/rocketmq-rust#1314

Revert "[ISSUE #1313]🔨Update Github Actions CI"

---

.github/workflows/automerge.yml
.github/workflows/remove-label-on-approve.yml
.github/workflows/sync-issue-labels.yml

[ISSUE #1336]🔨Update Github Actions CI

---

.github/ISSUE_TEMPLATE/refactor.yml

🔨Update refactor.yml

---

rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
rocketmq-client/src/consumer/consumer_impl/consume_message_pop_orderly_service.rs
rocketmq-client/src/consumer/consumer_impl/consume_message_service.rs
rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs
rocketmq-client/src/consumer/consumer_impl/process_queue.rs
rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
rocketmq-client/src/consumer/default_mq_push_consumer.rs
rocketmq-client/src/consumer/mq_consumer_inner.rs
rocketmq-client/src/consumer/pull_callback.rs

[ISSUE #1627]🚀Replace Client consumer's WeakArcMut<DefaultMQPushConsumerImpl> with ArcMut<DefaultMQPushConsumerImpl>🔥

---

rocketmq-store/src/pop.rs
rocketmq-store/src/pop/ack_msg.rs

[ISSSUE #1723]🚀Add AckMsg struct🍻

---

rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs

[ISSUE #1766]⚡️Replace ConsumerOrderInfoWrapper String with CheetahString🔥

---

rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs

[ISSUE #1781]🤡Optimize RebalancePushImpl#dispatch_pop_pull_request logic🔥

---

Cargo.lock
rocketmq-remoting/Cargo.toml
rocketmq-remoting/src/protocol/body/batch_ack.rs

[ISSUE #1855]🍓Optimize BatchAck BitSet like Java BitSet🚀

---

rocketmq-store/src/pop.rs
rocketmq-store/src/pop/ack_msg.rs
rocketmq-store/src/pop/batch_ack_msg.rs

[ISSUE #1858]⚡️AckMessage trait add get and set methods

---

rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs

[ISSUE #1854]Remove mut for PopProcessQueue test case

---

.github/workflows/auto_approve_pull_requests.yml

[ISSUE #2018]🔨Optimize Auto Approve Pull Requests

---

.github/workflows/auto_approve_pull_requests.yml

[ISSUE #2020]🔨Optimize Auto Approve Pull Requests

---

rocketmq-broker/src/processor/pop_message_processor.rs
rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
rocketmq-common/src/common/broker/broker_config.rs

[ISSUE #2025]⚗️Implement PopBufferMergeService#add_ack🚀

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/processor/pop_message_processor.rs

[ISSUE #2047]🧐Implement PopMessageProcessor#buildCkMsg🚀

---

rocketmq-broker/src/load_balance/message_request_mode_manager.rs

[ISSUE #2293]🤡Remove MessageRequestModeManager#set_message_request_mode clone⚡️

---

rocketmq-doc/_posts/2025-02-16-release-v0.4.0.md

[ISSUE #2569]📝Update relase v0.5.0 doc🔥

---

rocketmq-store/src/config/message_store_config.rs
rocketmq-store/src/message_store/local_file_message_store.rs

[ISSUE #3055]⚡️Optimize ReputMessageServiceInner#do_reput method

---

rocketmq-doc/_data/navigation.yml
rocketmq-doc/_docs/01-transaction-producer.md

[ISSUE #3352]🚀Add Transaction Producer documentation and update navigation structure💫

---

rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
rocketmq-store/src/ha/default_ha_service.rs
rocketmq-store/src/ha/general_ha_service.rs
rocketmq-store/src/ha/ha_service.rs

[ISSUE #3600]⚡️Improve HAService interface consistency and placeholder implementations

---

rocketmq-store/src/ha/default_ha_client.rs

[ISSUE #3733]🐛Fix commit log append offset calculation in HA client

---

distribution/config/broker/broker-simple.toml

[ISSUE #3768]📝Refactor broker-simple.toml to reorganize Broker Identity section

---

rocketmq-broker/src/broker/broker_pre_online_service.rs
rocketmq-broker/src/broker_runtime.rs
rocketmq-broker/src/out_api/broker_outer_api.rs

[ISSUE #3963]🚀Broker pre-online: master HA handshake loop, min-broker selection, and HA addr helper

---

rocketmq-broker/src/broker_runtime.rs
rocketmq-common/src/common/server/config.rs

test: added config test case for ServerConfig

---

rocketmq-remoting/src/remoting_server/server.rs

Fixes #3992 
Refactor event listener initialization to handle None case for channel_event_listener

[ISSUE #3992]♻️Refactor event listener initialization to handle None case for channel_event_listener
